### PR TITLE
haha

### PR DESCRIPTION
**Pull request by EnglishBaron**
@kikichu @alexz @allthefoxes @amandanp @anticomposite @barras @barras2 @c @cameron11598 @uyscuti @closedmouth @l235 @deskana @datguy @e @earwig @FastLizard4 @fluffernutter @gorillawarfare @grumble @idoh @samwalton9 @stwalkerster @bbb23 @jackmcbarn @k6ka @jianhui67 @justberry @keegan @krenair @ks0stm @niko @ksft @logan @marktraceur @matthew_ @mike1901 @notaspy @oshwah @pokefan95 @revent @sagan @samtar @slakr @snowolf @steinsplitter @tbloemink @ckoerner_WMF

### CODE REVIEW

**Comment by EnglishBaron** [comment]
@kikichu @alexz @allthefoxes @amandanp @anticomposite @barras @barras2 @c @cameron11598 @uyscuti @closedmouth @l235 @deskana @datguy @e @earwig @FastLizard4 @fluffernutter @gorillawarfare @grumble @idoh @samwalton9 @stwalkerster @bbb23 @jackmcbarn @k6ka @jianhui67 @justberry @keegan @krenair @ks0stm @niko @ksft @logan @marktraceur @matthew_ @mike1901 @notaspy @oshwah @pokefan95 @revent @sagan @samtar @slakr @snowolf @steinsplitter @tbloemink @ckoerner_WMF CLOSE IT AGAIN JUSTBERRY AND STWALKERSTER CLOSE MY THINGS HAHA

**Comment by cyberpower678** [comment]
@JustBerry I'm blocking these users as they come.  They can't comment on issues on the organization then. :)

**Comment by JustBerry** [comment]
@cyberpower678 Thanks. Chatted with stwalkerster via IRC, but they mentioned they will be busy for some time before they can work on resolving this issue.

**Comment by cyberpower678** [comment]
@JustBerry likewise.  I've been granted owner access to manage abuse.

**Comment by JustBerry** [comment]
@cyberpower678 Sounds good.

**Pull request closed without merging**
